# org.gradle.jvmargs=-Xms1g -Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
# org.gradle.daemon=false

org.gradle.caching=true
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.java.installations.fromEnv=JAVA_HOME,GRADLE_JAVA_HOME
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
android.usesSdkInManifest.disallowed=true

